### ISSUE TITLE
关于CASIA-B数据集逐帧对应的疑问

### ISSUE THREAD

**Issue by liguge** [ShinanZou/MSAFF#4]
我在跑一个多模态的代码。论文的题目是A Multi-Stage Adaptive Feature Fusion Neural Network for Multimodal Gait Recognition（10.1109/TBIOM.2024.3384704），我的疑问涉及论文的预处理部分，就是拼合剪影图数据和骨骼点数据。我下载了原始的CASIA-B数据集和您提供的CASIA-B-pose数据集。但是在合并数据集的时候，
[image](https://private-user-images.githubusercontent.com/19371493/342007640-88a81308-2b2d-4134-bca1-d6ae76b3d7e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMDc0MTUsIm5iZiI6MTcxOTEwNzExNSwicGF0aCI6Ii8xOTM3MTQ5My8zNDIwMDc2NDAtODhhODEzMDgtMmIyZC00MTM0LWJjYTEtZDZhZTc2YjNkN2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAxNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMWY0ODEzYmE3ZDQ5NjMxNWFhZmRjZWY2ODlkMGI1Y2U3MjE1ZTY3NTlhYzBjOTIwOWU2NTY1ZDUxNDg3MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YgdTAaOjOw2PyZ7OeQJBk68hPvAWFcSdkOJ29Efi2n4)
[image](https://private-user-images.githubusercontent.com/19371493/342007643-b210bfe3-c457-4ba5-9aff-76ce170966e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMDc0MTUsIm5iZiI6MTcxOTEwNzExNSwicGF0aCI6Ii8xOTM3MTQ5My8zNDIwMDc2NDMtYjIxMGJmZTMtYzQ1Ny00YmE1LTlhZmYtNzZjZTE3MDk2NmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAxNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2Y2ZiYmZhMGU2OTNmMzNlNzE3NjM2YzU3NDI1M2U5YzU3ZDRkYTUwN2I1ODUwZDAxYTJhZDg3ZTNhZWJlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iiBahnipZWiwCKpPoR09WEx6-ltJVZCZLduZdzRnA2U)
这样的话就导致数据集报错了，报错的原因是：89和98不对应，我下载的原始数据集的里面有89张图片，但是您给的数据集的原始数据里面有98张图片。我猜测是您下载的原始数据集的图片更多。001\bg-01\000，

我下载的图片数据集的示意图：
[image](https://private-user-images.githubusercontent.com/19371493/342007647-e775cf32-f871-45da-9ace-843b3c1f6d3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMDc0MTUsIm5iZiI6MTcxOTEwNzExNSwicGF0aCI6Ii8xOTM3MTQ5My8zNDIwMDc2NDctZTc3NWNmMzItZjg3MS00NWRhLTlhY2UtODQzYjNjMWY2ZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAxNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MzhhYzEwMjk0YzQwZDdmMDIxYzUwMGJiNjkzMWViMDYyZWFiMjdlYjk1ZTVlODE1ZGE4MjJhMzkxNTM4ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m4AYWDz6x96OtZh93YmbaObYvhmxdqT3FBo7rkeUU6k)
不知道能否分享一下您的原始数据的剪影图的图片呢？我是一个小白，还不知道怎么处理这种情况。使得图片的帧数变得一致。请问有什么思路可以提供吗？

**Comment by liguge** [comment]
请问或者可以一共一份关于制作pose的代码分享吗？

**Comment by ShinanZou** [comment]
I appreciate your interest. CASIA-B only released silhouette data at the beginning. When we did our experiments, we used Yolo to detect the human and HRNet to extract the pose from the RGB frame. This would result in a sequence that may have a few frames of RGB  with no pose or silhouette, which is unavoidable since it is not known what human detector was used to extract the silhouettes (this is the data that was released in '06, and probably no one but the original author knows what detector was used at the time). Eventually, there will be some sequences where the silhouette frame count does not match the pose frame count. We used data cleaning to remove frames that were silhouette-only or pose-only. The final result is that every frame has both silhouette and pose.

In addition, we may not give you the pose data of CASIA-B. The reasons are as follows: 1. We are not the publisher of CASIA-B data, and according to the CASIA-B data usage agreement, we have no right (without permission) to distribute any data to other teams. 2. It's been more than two years since we finished this experiment, and some of the data has been cleaned up by us (to save disk space).

Please understand some unavoidable reasons. You can clean the data by yourself according to our method; it is not difficult.

Also, the algorithm will be adapted to the CCGR dataset (https://github.com/ShinanZou/CCGR) within a month at most, and we will release the code. On CCGR, you may not have to clean the dataset yourself.

**Comment by weishiguan** [comment]
> 请问或者可以一共一份关于制作pose的代码分享吗？

请问作者提供的CASIA-B-pose数据集在哪里可以看到了，我并没有找到。期待您的回复

**Comment by ShinanZou** [comment]
There's already an update note, check it out at ReadMe!
